version: '3'

volumes:
  postgres_volume:
  redis-data:


services:
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1-alpine3.20
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181" # порт для клиентских соединений Zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # порт для клиентских соединений Zookeeper
      ZOOKEEPER_TICK_TIME: 2000 # основной интервал времени (в миллисекундах), используемый Zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper # указывает, что Kafka зависит от сервиса Zookeeper и будет запущен после него
    ports:
      - "9092:9092" # порт для клиентских соединений Kafka
    environment:
      KAFKA_BROKER_ID: 1 # уникальный идентификатор брокера Kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181' # адрес подключения к Zookeeper
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # указывает протоколы безопасности для слушателей
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 # указывает, какие адреса будут использоваться для общения с Kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # фактор репликации топика смещений
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 # время задержки перед началом перебалансировки группы
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # минимальное количество реплик, которые должны быть в синхронизации для топика состояния транзакции
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # фактор репликации топика состояния транзакции

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8082:8080" # порт для клиентских соединений Kafka UI
    environment:
      DYNAMIC_CONFIG_ENABLED: true
