// Code generated by http://github.com/gojuno/minimock (v3.4.1). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/spv-dev/auth/internal/repository.UserCache -o user_cache_minimock.go -n UserCacheMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	model "github.com/spv-dev/auth/internal/model"
)

// UserCacheMock implements mm_repository.UserCache
type UserCacheMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddUser          func(ctx context.Context, id int64, user *model.User) (err error)
	funcAddUserOrigin    string
	inspectFuncAddUser   func(ctx context.Context, id int64, user *model.User)
	afterAddUserCounter  uint64
	beforeAddUserCounter uint64
	AddUserMock          mUserCacheMockAddUser

	funcGetUser          func(ctx context.Context, id int64) (u1 model.User, err error)
	funcGetUserOrigin    string
	inspectFuncGetUser   func(ctx context.Context, id int64)
	afterGetUserCounter  uint64
	beforeGetUserCounter uint64
	GetUserMock          mUserCacheMockGetUser
}

// NewUserCacheMock returns a mock for mm_repository.UserCache
func NewUserCacheMock(t minimock.Tester) *UserCacheMock {
	m := &UserCacheMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddUserMock = mUserCacheMockAddUser{mock: m}
	m.AddUserMock.callArgs = []*UserCacheMockAddUserParams{}

	m.GetUserMock = mUserCacheMockGetUser{mock: m}
	m.GetUserMock.callArgs = []*UserCacheMockGetUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserCacheMockAddUser struct {
	optional           bool
	mock               *UserCacheMock
	defaultExpectation *UserCacheMockAddUserExpectation
	expectations       []*UserCacheMockAddUserExpectation

	callArgs []*UserCacheMockAddUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserCacheMockAddUserExpectation specifies expectation struct of the UserCache.AddUser
type UserCacheMockAddUserExpectation struct {
	mock               *UserCacheMock
	params             *UserCacheMockAddUserParams
	paramPtrs          *UserCacheMockAddUserParamPtrs
	expectationOrigins UserCacheMockAddUserExpectationOrigins
	results            *UserCacheMockAddUserResults
	returnOrigin       string
	Counter            uint64
}

// UserCacheMockAddUserParams contains parameters of the UserCache.AddUser
type UserCacheMockAddUserParams struct {
	ctx  context.Context
	id   int64
	user *model.User
}

// UserCacheMockAddUserParamPtrs contains pointers to parameters of the UserCache.AddUser
type UserCacheMockAddUserParamPtrs struct {
	ctx  *context.Context
	id   *int64
	user **model.User
}

// UserCacheMockAddUserResults contains results of the UserCache.AddUser
type UserCacheMockAddUserResults struct {
	err error
}

// UserCacheMockAddUserOrigins contains origins of expectations of the UserCache.AddUser
type UserCacheMockAddUserExpectationOrigins struct {
	origin     string
	originCtx  string
	originId   string
	originUser string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddUser *mUserCacheMockAddUser) Optional() *mUserCacheMockAddUser {
	mmAddUser.optional = true
	return mmAddUser
}

// Expect sets up expected params for UserCache.AddUser
func (mmAddUser *mUserCacheMockAddUser) Expect(ctx context.Context, id int64, user *model.User) *mUserCacheMockAddUser {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &UserCacheMockAddUserExpectation{}
	}

	if mmAddUser.defaultExpectation.paramPtrs != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by ExpectParams functions")
	}

	mmAddUser.defaultExpectation.params = &UserCacheMockAddUserParams{ctx, id, user}
	mmAddUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddUser.expectations {
		if minimock.Equal(e.params, mmAddUser.defaultExpectation.params) {
			mmAddUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddUser.defaultExpectation.params)
		}
	}

	return mmAddUser
}

// ExpectCtxParam1 sets up expected param ctx for UserCache.AddUser
func (mmAddUser *mUserCacheMockAddUser) ExpectCtxParam1(ctx context.Context) *mUserCacheMockAddUser {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &UserCacheMockAddUserExpectation{}
	}

	if mmAddUser.defaultExpectation.params != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Expect")
	}

	if mmAddUser.defaultExpectation.paramPtrs == nil {
		mmAddUser.defaultExpectation.paramPtrs = &UserCacheMockAddUserParamPtrs{}
	}
	mmAddUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmAddUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAddUser
}

// ExpectIdParam2 sets up expected param id for UserCache.AddUser
func (mmAddUser *mUserCacheMockAddUser) ExpectIdParam2(id int64) *mUserCacheMockAddUser {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &UserCacheMockAddUserExpectation{}
	}

	if mmAddUser.defaultExpectation.params != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Expect")
	}

	if mmAddUser.defaultExpectation.paramPtrs == nil {
		mmAddUser.defaultExpectation.paramPtrs = &UserCacheMockAddUserParamPtrs{}
	}
	mmAddUser.defaultExpectation.paramPtrs.id = &id
	mmAddUser.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmAddUser
}

// ExpectUserParam3 sets up expected param user for UserCache.AddUser
func (mmAddUser *mUserCacheMockAddUser) ExpectUserParam3(user *model.User) *mUserCacheMockAddUser {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &UserCacheMockAddUserExpectation{}
	}

	if mmAddUser.defaultExpectation.params != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Expect")
	}

	if mmAddUser.defaultExpectation.paramPtrs == nil {
		mmAddUser.defaultExpectation.paramPtrs = &UserCacheMockAddUserParamPtrs{}
	}
	mmAddUser.defaultExpectation.paramPtrs.user = &user
	mmAddUser.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmAddUser
}

// Inspect accepts an inspector function that has same arguments as the UserCache.AddUser
func (mmAddUser *mUserCacheMockAddUser) Inspect(f func(ctx context.Context, id int64, user *model.User)) *mUserCacheMockAddUser {
	if mmAddUser.mock.inspectFuncAddUser != nil {
		mmAddUser.mock.t.Fatalf("Inspect function is already set for UserCacheMock.AddUser")
	}

	mmAddUser.mock.inspectFuncAddUser = f

	return mmAddUser
}

// Return sets up results that will be returned by UserCache.AddUser
func (mmAddUser *mUserCacheMockAddUser) Return(err error) *UserCacheMock {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &UserCacheMockAddUserExpectation{mock: mmAddUser.mock}
	}
	mmAddUser.defaultExpectation.results = &UserCacheMockAddUserResults{err}
	mmAddUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddUser.mock
}

// Set uses given function f to mock the UserCache.AddUser method
func (mmAddUser *mUserCacheMockAddUser) Set(f func(ctx context.Context, id int64, user *model.User) (err error)) *UserCacheMock {
	if mmAddUser.defaultExpectation != nil {
		mmAddUser.mock.t.Fatalf("Default expectation is already set for the UserCache.AddUser method")
	}

	if len(mmAddUser.expectations) > 0 {
		mmAddUser.mock.t.Fatalf("Some expectations are already set for the UserCache.AddUser method")
	}

	mmAddUser.mock.funcAddUser = f
	mmAddUser.mock.funcAddUserOrigin = minimock.CallerInfo(1)
	return mmAddUser.mock
}

// When sets expectation for the UserCache.AddUser which will trigger the result defined by the following
// Then helper
func (mmAddUser *mUserCacheMockAddUser) When(ctx context.Context, id int64, user *model.User) *UserCacheMockAddUserExpectation {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("UserCacheMock.AddUser mock is already set by Set")
	}

	expectation := &UserCacheMockAddUserExpectation{
		mock:               mmAddUser.mock,
		params:             &UserCacheMockAddUserParams{ctx, id, user},
		expectationOrigins: UserCacheMockAddUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddUser.expectations = append(mmAddUser.expectations, expectation)
	return expectation
}

// Then sets up UserCache.AddUser return parameters for the expectation previously defined by the When method
func (e *UserCacheMockAddUserExpectation) Then(err error) *UserCacheMock {
	e.results = &UserCacheMockAddUserResults{err}
	return e.mock
}

// Times sets number of times UserCache.AddUser should be invoked
func (mmAddUser *mUserCacheMockAddUser) Times(n uint64) *mUserCacheMockAddUser {
	if n == 0 {
		mmAddUser.mock.t.Fatalf("Times of UserCacheMock.AddUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddUser.expectedInvocations, n)
	mmAddUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddUser
}

func (mmAddUser *mUserCacheMockAddUser) invocationsDone() bool {
	if len(mmAddUser.expectations) == 0 && mmAddUser.defaultExpectation == nil && mmAddUser.mock.funcAddUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddUser.mock.afterAddUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddUser implements mm_repository.UserCache
func (mmAddUser *UserCacheMock) AddUser(ctx context.Context, id int64, user *model.User) (err error) {
	mm_atomic.AddUint64(&mmAddUser.beforeAddUserCounter, 1)
	defer mm_atomic.AddUint64(&mmAddUser.afterAddUserCounter, 1)

	mmAddUser.t.Helper()

	if mmAddUser.inspectFuncAddUser != nil {
		mmAddUser.inspectFuncAddUser(ctx, id, user)
	}

	mm_params := UserCacheMockAddUserParams{ctx, id, user}

	// Record call args
	mmAddUser.AddUserMock.mutex.Lock()
	mmAddUser.AddUserMock.callArgs = append(mmAddUser.AddUserMock.callArgs, &mm_params)
	mmAddUser.AddUserMock.mutex.Unlock()

	for _, e := range mmAddUser.AddUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddUser.AddUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddUser.AddUserMock.defaultExpectation.Counter, 1)
		mm_want := mmAddUser.AddUserMock.defaultExpectation.params
		mm_want_ptrs := mmAddUser.AddUserMock.defaultExpectation.paramPtrs

		mm_got := UserCacheMockAddUserParams{ctx, id, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAddUser.t.Errorf("UserCacheMock.AddUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddUser.AddUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmAddUser.t.Errorf("UserCacheMock.AddUser got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddUser.AddUserMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmAddUser.t.Errorf("UserCacheMock.AddUser got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddUser.AddUserMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddUser.t.Errorf("UserCacheMock.AddUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddUser.AddUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddUser.AddUserMock.defaultExpectation.results
		if mm_results == nil {
			mmAddUser.t.Fatal("No results are set for the UserCacheMock.AddUser")
		}
		return (*mm_results).err
	}
	if mmAddUser.funcAddUser != nil {
		return mmAddUser.funcAddUser(ctx, id, user)
	}
	mmAddUser.t.Fatalf("Unexpected call to UserCacheMock.AddUser. %v %v %v", ctx, id, user)
	return
}

// AddUserAfterCounter returns a count of finished UserCacheMock.AddUser invocations
func (mmAddUser *UserCacheMock) AddUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddUser.afterAddUserCounter)
}

// AddUserBeforeCounter returns a count of UserCacheMock.AddUser invocations
func (mmAddUser *UserCacheMock) AddUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddUser.beforeAddUserCounter)
}

// Calls returns a list of arguments used in each call to UserCacheMock.AddUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddUser *mUserCacheMockAddUser) Calls() []*UserCacheMockAddUserParams {
	mmAddUser.mutex.RLock()

	argCopy := make([]*UserCacheMockAddUserParams, len(mmAddUser.callArgs))
	copy(argCopy, mmAddUser.callArgs)

	mmAddUser.mutex.RUnlock()

	return argCopy
}

// MinimockAddUserDone returns true if the count of the AddUser invocations corresponds
// the number of defined expectations
func (m *UserCacheMock) MinimockAddUserDone() bool {
	if m.AddUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddUserMock.invocationsDone()
}

// MinimockAddUserInspect logs each unmet expectation
func (m *UserCacheMock) MinimockAddUserInspect() {
	for _, e := range m.AddUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserCacheMock.AddUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddUserCounter := mm_atomic.LoadUint64(&m.afterAddUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddUserMock.defaultExpectation != nil && afterAddUserCounter < 1 {
		if m.AddUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserCacheMock.AddUser at\n%s", m.AddUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserCacheMock.AddUser at\n%s with params: %#v", m.AddUserMock.defaultExpectation.expectationOrigins.origin, *m.AddUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddUser != nil && afterAddUserCounter < 1 {
		m.t.Errorf("Expected call to UserCacheMock.AddUser at\n%s", m.funcAddUserOrigin)
	}

	if !m.AddUserMock.invocationsDone() && afterAddUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UserCacheMock.AddUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddUserMock.expectedInvocations), m.AddUserMock.expectedInvocationsOrigin, afterAddUserCounter)
	}
}

type mUserCacheMockGetUser struct {
	optional           bool
	mock               *UserCacheMock
	defaultExpectation *UserCacheMockGetUserExpectation
	expectations       []*UserCacheMockGetUserExpectation

	callArgs []*UserCacheMockGetUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserCacheMockGetUserExpectation specifies expectation struct of the UserCache.GetUser
type UserCacheMockGetUserExpectation struct {
	mock               *UserCacheMock
	params             *UserCacheMockGetUserParams
	paramPtrs          *UserCacheMockGetUserParamPtrs
	expectationOrigins UserCacheMockGetUserExpectationOrigins
	results            *UserCacheMockGetUserResults
	returnOrigin       string
	Counter            uint64
}

// UserCacheMockGetUserParams contains parameters of the UserCache.GetUser
type UserCacheMockGetUserParams struct {
	ctx context.Context
	id  int64
}

// UserCacheMockGetUserParamPtrs contains pointers to parameters of the UserCache.GetUser
type UserCacheMockGetUserParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// UserCacheMockGetUserResults contains results of the UserCache.GetUser
type UserCacheMockGetUserResults struct {
	u1  model.User
	err error
}

// UserCacheMockGetUserOrigins contains origins of expectations of the UserCache.GetUser
type UserCacheMockGetUserExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUser *mUserCacheMockGetUser) Optional() *mUserCacheMockGetUser {
	mmGetUser.optional = true
	return mmGetUser
}

// Expect sets up expected params for UserCache.GetUser
func (mmGetUser *mUserCacheMockGetUser) Expect(ctx context.Context, id int64) *mUserCacheMockGetUser {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &UserCacheMockGetUserExpectation{}
	}

	if mmGetUser.defaultExpectation.paramPtrs != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by ExpectParams functions")
	}

	mmGetUser.defaultExpectation.params = &UserCacheMockGetUserParams{ctx, id}
	mmGetUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUser.expectations {
		if minimock.Equal(e.params, mmGetUser.defaultExpectation.params) {
			mmGetUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUser.defaultExpectation.params)
		}
	}

	return mmGetUser
}

// ExpectCtxParam1 sets up expected param ctx for UserCache.GetUser
func (mmGetUser *mUserCacheMockGetUser) ExpectCtxParam1(ctx context.Context) *mUserCacheMockGetUser {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &UserCacheMockGetUserExpectation{}
	}

	if mmGetUser.defaultExpectation.params != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by Expect")
	}

	if mmGetUser.defaultExpectation.paramPtrs == nil {
		mmGetUser.defaultExpectation.paramPtrs = &UserCacheMockGetUserParamPtrs{}
	}
	mmGetUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUser
}

// ExpectIdParam2 sets up expected param id for UserCache.GetUser
func (mmGetUser *mUserCacheMockGetUser) ExpectIdParam2(id int64) *mUserCacheMockGetUser {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &UserCacheMockGetUserExpectation{}
	}

	if mmGetUser.defaultExpectation.params != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by Expect")
	}

	if mmGetUser.defaultExpectation.paramPtrs == nil {
		mmGetUser.defaultExpectation.paramPtrs = &UserCacheMockGetUserParamPtrs{}
	}
	mmGetUser.defaultExpectation.paramPtrs.id = &id
	mmGetUser.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetUser
}

// Inspect accepts an inspector function that has same arguments as the UserCache.GetUser
func (mmGetUser *mUserCacheMockGetUser) Inspect(f func(ctx context.Context, id int64)) *mUserCacheMockGetUser {
	if mmGetUser.mock.inspectFuncGetUser != nil {
		mmGetUser.mock.t.Fatalf("Inspect function is already set for UserCacheMock.GetUser")
	}

	mmGetUser.mock.inspectFuncGetUser = f

	return mmGetUser
}

// Return sets up results that will be returned by UserCache.GetUser
func (mmGetUser *mUserCacheMockGetUser) Return(u1 model.User, err error) *UserCacheMock {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &UserCacheMockGetUserExpectation{mock: mmGetUser.mock}
	}
	mmGetUser.defaultExpectation.results = &UserCacheMockGetUserResults{u1, err}
	mmGetUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUser.mock
}

// Set uses given function f to mock the UserCache.GetUser method
func (mmGetUser *mUserCacheMockGetUser) Set(f func(ctx context.Context, id int64) (u1 model.User, err error)) *UserCacheMock {
	if mmGetUser.defaultExpectation != nil {
		mmGetUser.mock.t.Fatalf("Default expectation is already set for the UserCache.GetUser method")
	}

	if len(mmGetUser.expectations) > 0 {
		mmGetUser.mock.t.Fatalf("Some expectations are already set for the UserCache.GetUser method")
	}

	mmGetUser.mock.funcGetUser = f
	mmGetUser.mock.funcGetUserOrigin = minimock.CallerInfo(1)
	return mmGetUser.mock
}

// When sets expectation for the UserCache.GetUser which will trigger the result defined by the following
// Then helper
func (mmGetUser *mUserCacheMockGetUser) When(ctx context.Context, id int64) *UserCacheMockGetUserExpectation {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("UserCacheMock.GetUser mock is already set by Set")
	}

	expectation := &UserCacheMockGetUserExpectation{
		mock:               mmGetUser.mock,
		params:             &UserCacheMockGetUserParams{ctx, id},
		expectationOrigins: UserCacheMockGetUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUser.expectations = append(mmGetUser.expectations, expectation)
	return expectation
}

// Then sets up UserCache.GetUser return parameters for the expectation previously defined by the When method
func (e *UserCacheMockGetUserExpectation) Then(u1 model.User, err error) *UserCacheMock {
	e.results = &UserCacheMockGetUserResults{u1, err}
	return e.mock
}

// Times sets number of times UserCache.GetUser should be invoked
func (mmGetUser *mUserCacheMockGetUser) Times(n uint64) *mUserCacheMockGetUser {
	if n == 0 {
		mmGetUser.mock.t.Fatalf("Times of UserCacheMock.GetUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUser.expectedInvocations, n)
	mmGetUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUser
}

func (mmGetUser *mUserCacheMockGetUser) invocationsDone() bool {
	if len(mmGetUser.expectations) == 0 && mmGetUser.defaultExpectation == nil && mmGetUser.mock.funcGetUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUser.mock.afterGetUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUser implements mm_repository.UserCache
func (mmGetUser *UserCacheMock) GetUser(ctx context.Context, id int64) (u1 model.User, err error) {
	mm_atomic.AddUint64(&mmGetUser.beforeGetUserCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUser.afterGetUserCounter, 1)

	mmGetUser.t.Helper()

	if mmGetUser.inspectFuncGetUser != nil {
		mmGetUser.inspectFuncGetUser(ctx, id)
	}

	mm_params := UserCacheMockGetUserParams{ctx, id}

	// Record call args
	mmGetUser.GetUserMock.mutex.Lock()
	mmGetUser.GetUserMock.callArgs = append(mmGetUser.GetUserMock.callArgs, &mm_params)
	mmGetUser.GetUserMock.mutex.Unlock()

	for _, e := range mmGetUser.GetUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmGetUser.GetUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUser.GetUserMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUser.GetUserMock.defaultExpectation.params
		mm_want_ptrs := mmGetUser.GetUserMock.defaultExpectation.paramPtrs

		mm_got := UserCacheMockGetUserParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUser.t.Errorf("UserCacheMock.GetUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUser.GetUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetUser.t.Errorf("UserCacheMock.GetUser got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUser.GetUserMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUser.t.Errorf("UserCacheMock.GetUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUser.GetUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUser.GetUserMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUser.t.Fatal("No results are set for the UserCacheMock.GetUser")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmGetUser.funcGetUser != nil {
		return mmGetUser.funcGetUser(ctx, id)
	}
	mmGetUser.t.Fatalf("Unexpected call to UserCacheMock.GetUser. %v %v", ctx, id)
	return
}

// GetUserAfterCounter returns a count of finished UserCacheMock.GetUser invocations
func (mmGetUser *UserCacheMock) GetUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUser.afterGetUserCounter)
}

// GetUserBeforeCounter returns a count of UserCacheMock.GetUser invocations
func (mmGetUser *UserCacheMock) GetUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUser.beforeGetUserCounter)
}

// Calls returns a list of arguments used in each call to UserCacheMock.GetUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUser *mUserCacheMockGetUser) Calls() []*UserCacheMockGetUserParams {
	mmGetUser.mutex.RLock()

	argCopy := make([]*UserCacheMockGetUserParams, len(mmGetUser.callArgs))
	copy(argCopy, mmGetUser.callArgs)

	mmGetUser.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserDone returns true if the count of the GetUser invocations corresponds
// the number of defined expectations
func (m *UserCacheMock) MinimockGetUserDone() bool {
	if m.GetUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserMock.invocationsDone()
}

// MinimockGetUserInspect logs each unmet expectation
func (m *UserCacheMock) MinimockGetUserInspect() {
	for _, e := range m.GetUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserCacheMock.GetUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserCounter := mm_atomic.LoadUint64(&m.afterGetUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserMock.defaultExpectation != nil && afterGetUserCounter < 1 {
		if m.GetUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserCacheMock.GetUser at\n%s", m.GetUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserCacheMock.GetUser at\n%s with params: %#v", m.GetUserMock.defaultExpectation.expectationOrigins.origin, *m.GetUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUser != nil && afterGetUserCounter < 1 {
		m.t.Errorf("Expected call to UserCacheMock.GetUser at\n%s", m.funcGetUserOrigin)
	}

	if !m.GetUserMock.invocationsDone() && afterGetUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UserCacheMock.GetUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserMock.expectedInvocations), m.GetUserMock.expectedInvocationsOrigin, afterGetUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserCacheMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddUserInspect()

			m.MinimockGetUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserCacheMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserCacheMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddUserDone() &&
		m.MinimockGetUserDone()
}
