package serviceerror

const (
	// InvalidRefreshToken "invalid refresh token"
	InvalidRefreshToken = "invalid refresh token"
	// FailedToGenerateToken "failed to generate token"
	FailedToGenerateToken = "failed to generate token"
	// FailedToGenerateRefreshToken "failed to generate refresh token"
	FailedToGenerateRefreshToken = "failed to generate refresh token"
	// FailedToGenerateAccessToken "failed to generate access token"
	FailedToGenerateAccessToken = "failed to generate access token"

	// MetadataIsNotProvided "metadata is not provided"
	MetadataIsNotProvided = "metadata is not provided"
	// AuthorizationHeaderIsNotProvided "authorization header is not provided"
	AuthorizationHeaderIsNotProvided = "authorization header is not provided"
	// InvalidAuthorizationPrefixFormat "invalid authorization prefix format"
	InvalidAuthorizationPrefixFormat = "invalid authorization prefix format"
	// AccessTokenIsInvalid "access token is invalid"
	AccessTokenIsInvalid = "access token is invalid"
	// FailedToGetAccessibleRoles  "failed to get accessible roles"
	FailedToGetAccessibleRoles = "failed to get accessible roles"
	// AccessDenied "access denied"
	AccessDenied = "access denied"

	// FailedToRunGRPCServer "failed to run GRPC server"
	FailedToRunGRPCServer = "failed to run GRPC server"
	// FailedToRunHTTPServer "failed to run HTTP server"
	FailedToRunHTTPServer = "failed to run HTTP server"
	// FailedToRunSwaggerServer "failed to run Swagger server"
	FailedToRunSwaggerServer = "failed to run Swagger server"
	// FailedToRunAuthServer "failed to run Auth server"
	FailedToRunAuthServer = "failed to run Auth server"
	// FailedToCloseSwaggerFile "failed to close swagger file: %v"
	FailedToCloseSwaggerFile = "failed to close swagger file: %v"

	// FailedToGetPGConfig "failed to get pg config: %v"
	FailedToGetPGConfig = "failed to get pg config: %v"
	// FailedToGetGRPCConfig "failed to get grpc config: %v"
	FailedToGetGRPCConfig = "failed to get grpc config: %v"
	// FailedToGetHTTPConfig "failed to get http config: %v"
	FailedToGetHTTPConfig = "failed to get http config: %v"
	// FailedToGetRedisConfig "failed to get redis config: %v"
	FailedToGetRedisConfig = "failed to get redis config: %v"
	// FailedToGetSwaggerConfig "failed to get swagger config: %v"
	FailedToGetSwaggerConfig = "failed to get swagger config: %v"
	// FailedToGetAuthConfig "failed to get auth config: %v"
	FailedToGetAuthConfig = "failed to get auth config: %v"
	// FailedToGetKafkaConfig "failed to get kafka producer config: %s"
	FailedToGetKafkaConfig = "failed to get kafka producer config: %s"
	// FailedToConnectToDatabase "failed to connect to database : %v"
	FailedToConnectToDatabase = "failed to connect to database : %v"
	// PingError "ping error: %v"
	PingError = "ping error: %v"
	// FailedToCreateKafkaSender "failed to create kafka sender: %v"
	FailedToCreateKafkaSender = "failed to create kafka sender: %v"

	// FailedToCloseRedisConnection "failed to close redis connection: %v"
	FailedToCloseRedisConnection = "failed to close redis connection: %v"
	// FailedToGetRedisConnection "failed to get redis connection: %v"
	FailedToGetRedisConnection = "failed to get redis connection: %v"

	// FailedToSendMessageInKafka "failed to send message in Kafka: %v"
	FailedToSendMessageInKafka = "failed to send message in Kafka: %v"

	// AuthHostNotFound "auth host not found"
	AuthHostNotFound = "auth host not found"
	// AuthPortNotFound "auth port not found"
	AuthPortNotFound = "auth port not found"
	// RefreshTokenSecretNotFound "refresh token secret not found"
	RefreshTokenSecretNotFound = "refresh token secret not found"
	// RefreshTokenExpirationNotFound "refresh token expiration not found"
	RefreshTokenExpirationNotFound = "refresh token expiration not found"
	// FailedToParseRefreshTokenExpiration "failed to parse refresh token expiration"
	FailedToParseRefreshTokenExpiration = "failed to parse refresh token expiration" // #nosec G101
	// AccessTokenSecretNotFound "access token secret not found"
	AccessTokenSecretNotFound = "access token secret not found"
	// AccessTokenExpirationNotFound "access token expiration not found"
	AccessTokenExpirationNotFound = "access token expiration not found"
	// FailedToParseAccessTokenExpiration "failed to parse access token expiration"
	FailedToParseAccessTokenExpiration = "failed to parse access token expiration" // #nosec G101

	// GRPCHostNotFound "gRPC host not found"
	GRPCHostNotFound = "gRPC host not found"
	// GRPCPortNotFound "gRPC port not found"
	GRPCPortNotFound = "gRPC port not found"

	// HTTPHostNotFound "http host not found"
	HTTPHostNotFound = "http host not found"
	// HTTPPortNotFound "http port not found"
	HTTPPortNotFound = "http port not found"

	// KafkaBrokersNotFound "kafka brokers not found"
	KafkaBrokersNotFound = "kafka brokers not found"
	// KafkaGroupIDNotFound "kafka group id not found"
	KafkaGroupIDNotFound = "kafka group id not found"

	// PGDsnNotFound "pg dsn not found"
	PGDsnNotFound = "pg dsn not found"

	// RedisHostNotFound "redis host not found"
	RedisHostNotFound = "redis host not found"
	// RedisPortNotFound "redis port not found"
	RedisPortNotFound = "redis port not found"
	// RedisConnectionTimeoutNotFound "redis connection timeout not found"
	RedisConnectionTimeoutNotFound = "redis connection timeout not found"
	// FailedToParseConnectionTimeout "failed to parse connection timeout"
	FailedToParseConnectionTimeout = "failed to parse connection timeout"
	// RedisMaxIdleNotFound "redis max idle not found"
	RedisMaxIdleNotFound = "redis max idle not found"
	// FailedToParseMaxIdle  "failed to parse max idle"
	FailedToParseMaxIdle = "failed to parse max idle"
	// RedisIdleTimeoutNotFound "redis idle timeout not found"
	RedisIdleTimeoutNotFound = "redis idle timeout not found"
	// FailedToParseIdleTimeout "failed to parse idle timeout"
	FailedToParseIdleTimeout = "failed to parse idle timeout"

	// SwaggerHostNotFound "swagger host not found"
	SwaggerHostNotFound = "swagger host not found"
	// SwaggerPortNotFound "swagger port not found"
	SwaggerPortNotFound = "swagger port not found"

	// EmptyDataWhenCreateUser "Пустые данные при создании пользователя"
	EmptyDataWhenCreateUser = "Пустые данные при создании пользователя"
	// EmptyDataWhenUpdateUser "Пустые данные при изменении пользователя"
	EmptyDataWhenUpdateUser = "Пустые данные при изменении пользователя"

	// UnexpectedTokenSigningMethod "unexpected token signing method"
	UnexpectedTokenSigningMethod = "unexpected token signing method"
	// InvalidToken "invalid token: %v"
	InvalidToken = "invalid token: %v"
	// InvalidTokenClaim "invalid token claim"
	InvalidTokenClaim = "invalid token claim"
)
